wandb_version: 1

lr:
  desc: null
  value: 0.015076398427336424
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.19.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1736855491
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 105
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.10.16
      5: 0.19.2
      8:
      - 5
      13: linux-x86_64
batch-size:
  desc: null
  value: 32
learning-rate:
  desc: null
  value: 0.015076398427336424
